### ISSUE TITLE
plugin not working correctly in repeat mode for custom html

### ISSUE THREAD

**Issue by syedsfayaz** [yesoreyeram/yesoreyeram-boomsummary-panel#8]
@yesoreyeram 

This plugin is working great. I am seeing some issue for repeat mode. Can you please tell me how can I attain it.  If I choose auto template or jumbo it works really great. 
![image](https://user-images.githubusercontent.com/26099918/62811378-4a027500-bab6-11e9-8523-433fe46324ed.png)

But I am seeing issue when I have custom html for this.  Here is with out repeat mode. 
![image](https://user-images.githubusercontent.com/26099918/62811409-643c5300-bab6-11e9-93da-ad7b61c58753.png)

But when I choose repeat. The UI is crumbled. Can you Please assist how I can get it to work correctly. 
![image](https://user-images.githubusercontent.com/26099918/62811462-9483f180-bab6-11e9-91a0-e3ff0d02987f.png)

**Comment by syedsfayaz** [comment]
Got it to work some how. But looks like I need to add some space between each value. Will work on it. 

![image](https://user-images.githubusercontent.com/26099918/62812494-d3b44180-baba-11e9-89d6-d19688508077.png)

**Comment by yesoreyeram** [comment]
You may have incorrect CSS settings. Please check.

**Comment by syedsfayaz** [comment]
I did not add any CSS in the settings. I will take a look.

**Comment by maneetgoyal** [comment]
In continuation to what @syedsfayaz asked, I am trying to assign some styling property to those div elements (build, sanity, junits, etc). Is there any way I can apply styling via classes? I want to attach the following CSS to these elements individually:

```css
#pointer {
      width: 200px;
      height: 40px;
      position: relative;
      background: red;
    }
    #pointer:after {
      content: "";
      position: absolute;
      left: 0;
      bottom: 0;
      width: 0;
      height: 0;
      border-left: 20px solid white;
      border-top: 20px solid transparent;
      border-bottom: 20px solid transparent;
    }
    #pointer:before {
      content: "";
      position: absolute;
      right: -20px;
      bottom: 0;
      width: 0;
      height: 0;
      border-left: 20px solid red;
      border-top: 20px solid transparent;
      border-bottom: 20px solid transparent;
    }
```

For spacing we added border/padding but the style was added inline in the custom HTML template. Can we do it via CSS class?
